version: "3.8"

services:
  svelte-client:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - go-server
  go-server:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - GIN_MODE=${GIN_MODE}
